version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blind_chess
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/blind_chess
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data:
